### ISSUE TITLE
'Call to undefined method [mergeConfigFrom]'

### ISSUE THREAD

**Issue by lucasRolff** [spekkionu/laravel-assetcachebuster#5]
Hi,

When trying to use this module in Laravel 5, I get following message:

```
php artisan vendor:publish --provider=Spekkionu\Assetcachebuster\AssetcachebusterServiceProvider
exception 'BadMethodCallException' with message 'Call to undefined method [mergeConfigFrom]' in /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:140
Stack trace:
#0 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/spekkionu/assetcachebuster/src/Spekkionu/Assetcachebuster/AssetcachebusterServiceProvider.php(38): Illuminate\Support\ServiceProvider->__call('mergeConfigFrom', Array)
#1 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/spekkionu/assetcachebuster/src/Spekkionu/Assetcachebuster/AssetcachebusterServiceProvider.php(38): Spekkionu\Assetcachebuster\AssetcachebusterServiceProvider->mergeConfigFrom('/Users/LucasRol...', 'assetcachebuste...')
#2 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(393): Spekkionu\Assetcachebuster\AssetcachebusterServiceProvider->register()
#3 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\Foundation\Application->register(Object(Spekkionu\Assetcachebuster\AssetcachebusterServiceProvider))
#4 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(369): Illuminate\Foundation\ProviderRepository->load(Array)
#5 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(15): Illuminate\Foundation\Application->registerConfiguredProviders()
#6 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(151): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#7 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(180): Illuminate\Foundation\Application->bootstrapWith(Array)
#8 /Users/LucasRolff/Projects/mauran_fucks_me/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#9 /Users/LucasRolff/Projects/mauran_fucks_me/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}
```

Do you know why? And is the package fully tested with 5.x?

**Comment by lucasRolff** [comment]
Turns out my laravel version was just wrong - works awesome!

**Comment by lucasRolff** [comment]
I've decided to reopen it anyway, since it seems the method mergeConfigFrom is indeed not a part of Laravel5 - I wasn't able to do composer install on a new laravel project without it failing.

**Comment by spekkionu** [comment]
The mergeConfigFrom method is in Laravel 5.

Here is the method in the source of Illuminate/Support/ServiceProvider.php 
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Support/ServiceProvider.php#L60

Here is the documentation on loading configuration from a package. 
http://laravel.com/docs/5.0/packages#configuration

Can you confirm the version of the laravel/framework package you are using? 
Did you install laravel with the laravel installer or composer create-project?

**Comment by lucasRolff** [comment]
Hi @spekkionu,

I did install it using composer create-project - laravel/framework:

```json
            "name": "laravel/framework",
            "version": "v5.0.6",
            "source": {
                "type": "git",
                "url": "https://github.com/laravel/framework.git",
                "reference": "43637b796f1ac0b1a960984231251ff04b438006"
            }
```
